### ISSUE TITLE
trpc-shield not working in a monorepo

### ISSUE THREAD

**Issue by gablabelle** [omar-dulaimi/trpc-shield#1]
# Bug report

- [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

`trpc-shield` doesn't seem to work in the context of a monorepo. Maybe I'm just doing something wrong?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I have created a monorepo so you can observe the behaviour. Available at:
https://github.com/gablabelle/bug-reproduction-monorepo-trpc-shield

1- `git clone` repo
2- `yarn install`
3- `yarn dev`
4- Context is located at `apps/my-t3-app/src/server/router/context.ts`

## Expected behavior

Should deny the `example.hello` call
<img width="692" alt="Screen Shot 2022-07-17 at 12 04 32" src="https://user-images.githubusercontent.com/1565793/179409850-a5512232-ee91-4db3-9867-0a1c1757ba34.png">

but it doesn't

![Screen Shot 2022-07-17 at 12 05 33](https://user-images.githubusercontent.com/1565793/179410238-0d447277-5d7f-45c0-841d-0cbd197bce43.png)

**Comment by omar-dulaimi** [comment]
Did you apply the permissions as a middleware in your app router?

```ts
import { permissions } from "../../../prisma/permissions";

export const appRouter = createRouter()
  .middleware(permissions)
  .transformer(superjson)
  .merge("example.", exampleRouter)
  .merge("auth.", authRouter);
```

also,  change `example.hello` to `hello`.

**Comment by gablabelle** [comment]
@omar-dulaimi, thanks for your quick response

Yes middleware was added.
![Screen Shot 2022-07-17 at 14 37 12](https://user-images.githubusercontent.com/1565793/179420062-6d5a9d8e-519a-4bf6-874b-c3f5996aaf45.png)
 
And indeed changing the name from `example.hello` to `hello`, etc ... **fixed the issue**.

**Thanks a lot**, really appreciative of your help.

**Comment by gablabelle** [comment]
@omar-dulaimi but one thing though... I'm just now realizing that this means that the `fallbackRule: deny` doesn't actually work?

**Comment by omar-dulaimi** [comment]
> @omar-dulaimi but one thing though... I'm just now realizing that this means that the `fallbackRule: deny` doesn't actually work?

Hey, I totally forgot to respond to you, my bad. Anyway, a PR came that fixed this issue and it's now available in the latest release. Please create a new issue next time, it's better that way to not forget about it.
