### ISSUE TITLE
When a rule returns false, the library throws an error 500

### ISSUE THREAD

**Issue by benjammartin** [omar-dulaimi/trpc-shield#11]
# Question about tRPC Shield

When a rule returns false, the library throws an error 500. I would like to know if it's normal behavior.

<img width="349" alt="Capture_decran_2023-01-16_a_22 48 53" src="https://user-images.githubusercontent.com/6057521/212772280-bfb4413a-090f-4ab4-bddd-dad6a36112a3.png">

**Comment by omar-dulaimi** [comment]
It should return something else like 401 maybe. 

For now, you could change it like this:

```js
  {
    fallbackError: new TRPCError({ code: 'UNAUTHORIZED', message: 'Not allowed' })
  }
```

**Comment by benjammartin** [comment]
Thx you very much. It's working.
