### ISSUE TITLE
Unexpected behavior with prisma-trpc-generator

### ISSUE THREAD

**Issue by imsanchez** [omar-dulaimi/trpc-shield#13]
I'd like to verify this is a bug and not an issue with my configurations before further investigation.

# Bug report

- [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I'm using this in combination with [prisma-trpc-generator](https://github.com/omar-dulaimi/prisma-trpc-generator#readme) (Thank you @omar-dulaimi for building these!). I am also using SuperJSON transformer end-to-end.

I started using my own permissions, instead of the ones generated with all allow defaults.

I am working with the path `account.findUnique`.

To keep things short and concise, this pattern does not work (results in fallback denial):
```
export const permissions = shield<Context>(
  {
    query: {
      findUniqueAccount: allow,
      ...
    },
  },
  {
    fallbackRule: deny,
  },
);
```
but this does work:
```
export const permissions = shield<Context>(
  {
    query: {
      findUnique: allow,
      ...
    },
  },
  {
    fallbackRule: deny,
  },
);
```

This ties back to the issue raised here: https://github.com/omar-dulaimi/trpc-shield/issues/1#issuecomment-1186587182 and the example permission  (https://github.com/omar-dulaimi/trpc-shield/blob/master/example/prisma/shield/shield.ts) also follows the earlier pattern, not the latter which is working.

## To Reproduce

Things are set up pretty traditionally. Shield is working, but the nested router mapping does not.

```
export const appRouter = t.router({
  account: accountsRouter,
});
```

## Additional context

Although it's not working as intended, I've observed a singular namespace will work as intended.

This works:
```
export const permissions = shield<Context>(
  {
    account: {
      query: {
        findMany: allow,
      },
    },
  },
  {
    fallbackRule: deny,
  },
);
 ```
This does not work:
```
export const permissions = shield<Context>(
  {
    account: {
      query: {
        findMany: allow,
      },
    },
    player: {
      query: {
        findUnique: allow,
      },
    },
  },
  {
    fallbackRule: deny,
  },
);
 ```

Hoping for some clarity on the correct working patterns.

**Comment by imsanchez** [comment]
Apologies, the namespace pattern appears to be working:

```
export const permissions = shield<Context>({
    account: {
      query: {
        findUnique: isAuthenticated,
      },
    },
});
```

**Comment by omar-dulaimi** [comment]
I just tested your first snippet using the example code on this repo, and it worked fine. Are you sure you're testing it right?

```
export const permissions = shield<Context>(
  {
    query: {
      findUniqueUser: allow,
    },
  },
  {
    fallbackRule: deny,
  },
);
```

I think you may have disabled `showModelNameInProcedure` in the generator options. For the shield to work correctly, it must have matching procedure name for each operation defined.

So, if the procedure was `findMany`, the operation should have the same name `findMany` for the shield to be able to match them correctly.

To make things simpler, I think I should make the generator pass the `showModelNameInProcedure` value to shield generator.

**Comment by imsanchez** [comment]
This is true @omar-dulaimi reenabling `showModelNameInProcedure ` fixed the issue. I guess it doesn't work the way I thought it would. Pivoting my application to work with the change was quick and easy. 

Everything is working as intended, I appreciate your insightful and thorough answer.
