### ISSUE TITLE
Unclear how to access "parent" 

### ISSUE THREAD

**Issue by erickreutz** [omar-dulaimi/trpc-shield#16]
In the examples on the home page you have the following as a rule:

```js
const isOwner = rule<Context>()(async (ctx, type, path, input, rawInput) => {
  return ctx.user.items.some((id) => id === parent.id)
})
```

Where is parent coming from? How to use trpc-shield to define a rule and access the object or parent in question is unclear.

**Comment by omar-dulaimi** [comment]
Oh I must have missed that after forking from the original grpahgl shield repo. Thanks for bringing it to my attention, will fix it soon
