### ISSUE TITLE
Permissions of namespace routes collide if they have the same name

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [omar-dulaimi/trpc-shield#17]
# Bug report

- [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I group all my routes in namespaces and usually have the same name inside a namespace. If that's the case, the first route permissions are applied.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Define the following permissions

```
const permissions = shield<Context>(
  {
    users: {
      mutation: {
        createOne: and(isAuthenticated, isAdmin)
      }
    },
    posts: {
      mutation: {
        createOne: isAuthenticated,
      }
    }
  }
);
```
The `isAdmin` guard is called when making a request to `posts.createOne`

## Expected behavior

`isAdmin` is not executed and the proper guards are executed.

## behavior

`isAdmin` is executed when calling `posts.createOne`

**Comment by enrique-fernandez-polo** [comment]
I see the problems comes from these lines

https://github.com/omar-dulaimi/trpc-shield/blob/0769f668548808ac7258ab6078deebfc3684b63a/src/generator.ts#L38-L45

It's not checking if the namespace is the same. What if instead of iterating through the object, we get the namespace from `opWithPath[0]`? Makes sense?

**Comment by omar-dulaimi** [comment]
Hey @enrique-fernandez-polo 
Thank you for reporting and fixing this bug, and I apologize for the delay. Indeed your solution fixes the problem at hand.

But I'll merge PR #19 instead of PR #18 as it fixes types as well. Thank you again :)

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/trpc-shield/releases/tag/0.4.3
