### ISSUE TITLE
Does this library support child (namespaced) routers?

### ISSUE THREAD

**Issue by ZZzz-hub** [omar-dulaimi/trpc-shield#8]
If supported, how to write the config object?

![image](https://user-images.githubusercontent.com/112529867/211478071-09bb17ad-b6e8-4a2b-8270-5076e1fceece.png)

**Comment by ngajhede** [comment]
Would be nice to be able to do this. +1

**Comment by omar-dulaimi** [comment]
Seems like a useful addition. Will look into it soon.

In the meantime, consider sponsoring this project or at least starring it :)

**Comment by omar-dulaimi** [comment]
Should be done in https://github.com/omar-dulaimi/trpc-shield/releases/tag/0.4.0

**Comment by omar-dulaimi** [comment]
Hey @moranbw 
Could open a new issue/feature request for this?
I usually forget closed issues
